/** Audit action names — append only, never reuse for a different meaning. */
export const AUDIT = {
  USER_REGISTERED: 'USER_REGISTERED',
  USER_LOGIN: 'USER_LOGIN',
  USER_LOGIN_FAILED: 'USER_LOGIN_FAILED',
  USER_LOGOUT: 'USER_LOGOUT',
  USER_LOGOUT_ALL: 'USER_LOGOUT_ALL',
  PASSWORD_CHANGED: 'PASSWORD_CHANGED',
  PASSWORD_RESET_REQUESTED: 'PASSWORD_RESET_REQUESTED',
  PASSWORD_RESET: 'PASSWORD_RESET',
  TOKEN_REUSE_DETECTED: 'TOKEN_REUSE_DETECTED',
  PROFILE_UPDATED: 'PROFILE_UPDATED',
  USER_DISABLED: 'USER_DISABLED',
  USER_ENABLED: 'USER_ENABLED',
  VERIFICATION_SENT: 'VERIFICATION_SENT',
  VERIFICATION_COMPLETED: 'VERIFICATION_COMPLETED',
} as const;

export type AuditAction = (typeof AUDIT)[keyof typeof AUDIT];
