/** Audit action names — append only, never reuse for a different meaning. */
export const AUDIT = {
  USER_REGISTERED: 'USER_REGISTERED',
  USER_LOGIN: 'USER_LOGIN',
  USER_LOGIN_FAILED: 'USER_LOGIN_FAILED',
  USER_LOGOUT: 'USER_LOGOUT',
  USER_LOGOUT_ALL: 'USER_LOGOUT_ALL',
  PASSWORD_CHANGED: 'PASSWORD_CHANGED',
  PASSWORD_RESET_REQUESTED: 'PASSWORD_RESET_REQUESTED',
  PASSWORD_RESET: 'PASSWORD_RESET',
  TOKEN_REUSE_DETECTED: 'TOKEN_REUSE_DETECTED',
  PROFILE_UPDATED: 'PROFILE_UPDATED',
  USER_DISABLED: 'USER_DISABLED',
  USER_ENABLED: 'USER_ENABLED',
  VERIFICATION_SENT: 'VERIFICATION_SENT',
  VERIFICATION_COMPLETED: 'VERIFICATION_COMPLETED',

  // Stage 3 — employee & role management
  EMPLOYEE_CREATED: 'EMPLOYEE_CREATED',
  EMPLOYEE_UPDATED: 'EMPLOYEE_UPDATED',
  EMPLOYEE_DISABLED: 'EMPLOYEE_DISABLED',
  EMPLOYEE_ENABLED: 'EMPLOYEE_ENABLED',
  ROLE_CREATED: 'ROLE_CREATED',
  ROLE_UPDATED: 'ROLE_UPDATED',
  ROLE_DELETED: 'ROLE_DELETED',
  ROLE_ASSIGNED: 'ROLE_ASSIGNED',
  ROLE_REVOKED: 'ROLE_REVOKED',
  ROLE_PERMISSIONS_UPDATED: 'ROLE_PERMISSIONS_UPDATED',

  // Stage 4 — catalog & inventory
  CATEGORY_CREATED: 'CATEGORY_CREATED',
  CATEGORY_UPDATED: 'CATEGORY_UPDATED',
  CATEGORY_DISABLED: 'CATEGORY_DISABLED',
  CATEGORY_DELETED: 'CATEGORY_DELETED',
  BRAND_CREATED: 'BRAND_CREATED',
  BRAND_UPDATED: 'BRAND_UPDATED',
  BRAND_DISABLED: 'BRAND_DISABLED',
  BRAND_DELETED: 'BRAND_DELETED',
  PRODUCT_CREATED: 'PRODUCT_CREATED',
  PRODUCT_UPDATED: 'PRODUCT_UPDATED',
  PRODUCT_DISABLED: 'PRODUCT_DISABLED',
  PRODUCT_DELETED: 'PRODUCT_DELETED',
  PRODUCT_IMAGE_ADDED: 'PRODUCT_IMAGE_ADDED',
  PRODUCT_IMAGE_UPDATED: 'PRODUCT_IMAGE_UPDATED',
  PRODUCT_IMAGE_DELETED: 'PRODUCT_IMAGE_DELETED',
  PRODUCT_IMAGES_REORDERED: 'PRODUCT_IMAGES_REORDERED',
  PRODUCT_SPECIFICATIONS_UPDATED: 'PRODUCT_SPECIFICATIONS_UPDATED',
  SPECIFICATION_CREATED: 'SPECIFICATION_CREATED',
  SPECIFICATION_UPDATED: 'SPECIFICATION_UPDATED',
  SPECIFICATION_DELETED: 'SPECIFICATION_DELETED',
  INVENTORY_ADJUSTED: 'INVENTORY_ADJUSTED',
  INVENTORY_UPDATED: 'INVENTORY_UPDATED',

  // Stage 5 — cart & checkout preview
  CART_ITEM_ADDED: 'CART_ITEM_ADDED',
  CART_ITEM_UPDATED: 'CART_ITEM_UPDATED',
  CART_ITEM_REMOVED: 'CART_ITEM_REMOVED',
  CART_CLEARED: 'CART_CLEARED',
  CHECKOUT_PREVIEW_CREATED: 'CHECKOUT_PREVIEW_CREATED',

  // Stage 6 — orders & inventory reservation
  ORDER_CREATED: 'ORDER_CREATED',
  ORDER_CANCELLED: 'ORDER_CANCELLED',
  ORDER_STATUS_UPDATED: 'ORDER_STATUS_UPDATED',
  ORDER_RESERVATION_CREATED: 'ORDER_RESERVATION_CREATED',
  ORDER_RESERVATION_RELEASED: 'ORDER_RESERVATION_RELEASED',
} as const;

export type AuditAction = (typeof AUDIT)[keyof typeof AUDIT];
